### ISSUE TITLE
.env file not created in deployment viewer

### ISSUE THREAD

**Issue by conorw** [ionos-deploy-now/template-renderer-action#1]
I'm currently using deploy-now with the default configuration.
I have a .env.template file located in the .deploy-now/[projectname] folder
The render templates deploy step seems to execute OK, but no .env file is created i.e. when I view the deployment files in the 'deployment viewer', no .env file has been created in the root folder.
Is this expected behaviour or a bug?
Thanks
```

      - name: Render templates
        uses: ionos-deploy-now/template-renderer-action@v2
        id: template
        with:
          deployment-id: ${{ matrix.deployment-id }}
          data: "[${{ steps.deployment.outputs.template-variables }}, ${{ toJson(secrets) }}]"
          input-directory: deployment
          output-directory: deployment
          intermediate-data-file: deployment/.template-renderer-data
```

**Comment by jazzfreunde-ingolstadt** [comment]
I ran into the same problem. I have testet both the method described in the official [documentation](https://docs.ionos.space/docs/runtime-configuration/#application-configuration) as well as the method i came accross in the [example project](https://github.com/ionos-deploy-now/symfony-starter/blob/main/.env)

**Comment by jazzfreunde-ingolstadt** [comment]
Figured it out after setting up the project once more. Templates are not generated during the deployment workflow. It is an optional step during the build phase, which is only included in the workflow yaml if you fill out the template section in the setup assistant.

So you should add a step in your build workflow like:
```yaml
- name: Render templates
        uses: ionos-deploy-now/template-renderer-action@v2
        id: template
        with:
          input-directory: .deploy-now/project-name
          output-directory: ${{ env.DEPLOYMENT_FOLDER }}
          intermediate-data-file: ${{ env.DEPLOYMENT_FOLDER }}/.template-renderer-data
```
